name 'gb-puppet'
version '0.0.1'
source 'https://github.com/naps62/gb-puppet'
author 'Miguel Palhas'
summary 'Group Buddies Puppet module'
description 'Used to provision Group Buddies web servers'
project_page 'https://github.com/naps62/gb-puppet'

dependency 'puppetlabs-apt', '>= 1.4.0'
dependency 'puppetlabs-nginx', '>= 0.0.5'
dependency 'puppetlabs-nodejs', '>= 0.4.0'
dependency 'puppetlabs-postgresql', '>= 3.1.0'
dependency 'Aethylred-git', '>= 0.1.2'
dependency 'puppet-rvm', '>= 1.0.0'
