#!/bin/sh

LSB_RELEASE="trusty"
GB_PUPPET_VERSION="0.1.4"
MANIFEST="https://raw.githubusercontent.com/groupbuddies/gb-puppet/master/setup/ubuntu-trusty.pp"

DEB="puppetlabs-release-${LSB_RELEASE}.deb"
DEB_PROVIDES="/etc/apt/sources.list.d/puppetlabs.list" # Assume that this file's existence means we have Puppet Labs repo added

if [ ! -e $DEB_PROVIDES ]; then
  wget -q http://apt.puppetlabs.com/$DEB
  sudo dpkg -i $DEB
fi

sudo apt-get update
sudo apt-get install --yes puppet
puppet module install groupbuddies-gb --force --version $GB_PUPPET_VERSION

curl $MANIFEST > /tmp/manifest.pp
puppet apply /tmp/manifest.pp
